version: "3"
services:
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_DB: ${DATABASE_NAME}
    networks:
      - chatter-node
  app:
    image: chatter-node-backend
    depends_on:
      - db
    ports:
      - 8080:8080
    networks:
      - chatter-node

networks:
  chatter-node:
    driver: bridge


